### ISSUE TITLE
Неверное использование case

### ISSUE THREAD

**Issue by frontgirl** [BRust1981/NetologyDiplom#10]
https://github.com/BRust1981/NetologyDiplom/blob/43e1bbcb4b4355f6adc49ca7cd8cad04ec24b1cb/game.js#L326

Такое использование case затрудняет чтение кода. Единственное, для чего уместно использовать case - это для преобразования символа в значение в этом методе. Правильный вариант:

switch (symbol) {
			case 'x': return 'wall';
			case '!': return 'lava';
                         default: return undefined;
}

Если перед switch нужно выполнить проверку - используйте if.

**Comment by BRust1981** [comment]
Согласен, главное вернуть wall и lava, остальное - по дефолту вернется андефайнд. Исправил.
