### ISSUE TITLE
Для решения данной задачи лучше подойдет метод map

### ISSUE THREAD

**Issue by frontgirl** [BRust1981/NetologyDiplom#11]
https://github.com/BRust1981/NetologyDiplom/blob/43e1bbcb4b4355f6adc49ca7cd8cad04ec24b1cb/game.js#L339

Метод массива map специально создан для того, чтобы на основе имеющегося массива получить новый, проделав какое-то действие или действия с каждым элементом массива. Пример: let newArray = oldArray.map((item)=>{return item*2;}); - в данном случае получаем в переменной newArray массив из элементов oldArray, каждый из которых умножен на 2. Такой способ избавит вас от двух буферных переменных и позволит упростить код.

А вот получить из строки массив символов можно довольно удобно с помощью оператора spread вот так: [...myString]

**Comment by BRust1981** [comment]
Поправил в методе createGrid, думал также поменять метод createActors. Я правильно понимаю, что там лучше применить reduce?
