### ISSUE TITLE
Обе функции должны быть методами соответствующего класса (там, где они используются).

### ISSUE THREAD

**Issue by frontgirl** [BRust1981/NetologyDiplom#4]
https://github.com/BRust1981/NetologyDiplom/blob/43e1bbcb4b4355f6adc49ca7cd8cad04ec24b1cb/game.js#L3

Смотрите, класс сам по себе целостный объект, который должен содержать все данные и нужные для работы с ними методы. Можно было бы каким-то образом оправдать вынесение "сервисных" функций, если бы они использовались несколько раз, в разных классах, но в вашем коде каждая из 2х функций используется по одному разу, в конкретном классе. Поэтому - делаем их методами.

**Comment by BRust1981** [comment]
Убрал внешние функции. Одну совсем - она применяется один раз.
