### ISSUE TITLE
Ошибка в алгоритме проверки

### ISSUE THREAD

**Issue by frontgirl** [BRust1981/NetologyDiplom#7]
https://github.com/BRust1981/NetologyDiplom/blob/43e1bbcb4b4355f6adc49ca7cd8cad04ec24b1cb/game.js#L235

Вы верно делаете проверку на "стену" и "лаву" (кроме использования switch). А если не не "стена", и не "лава" - должно быть два цикла, по оси x и y. И далее нужно во внутреннем массиве посмотреть в каждую ячейку проверяемой области и если в ячейке не undefined - вернуть значение, находящееся в ячейке, каким бы оно ни было. Можете вынести это в отдельную фунцию, но нужно всего 2 цикла, а не 3, как сейчас. Просто идем по ячейкам, построчно, и смотрим что внутри, сравнивая с undefined.

**Comment by BRust1981** [comment]
В функцию spaceXY, которая находит занимаемое объектом пространство, отправил текущий грид. Пробег один, по целым точкам пространства.
