### ISSUE TITLE
Ошибка в способе копирования объекта

### ISSUE THREAD

**Issue by frontgirl** [BRust1981/NetologyDiplom#8]
https://github.com/BRust1981/NetologyDiplom/blob/43e1bbcb4b4355f6adc49ca7cd8cad04ec24b1cb/game.js#L307

Нужно скопировать dictionary в this.dictionary, это делается обычным присваиванием

**Comment by BRust1981** [comment]
Да, исправил в issues "элементы словаря не должны быть свойствами LevelParser "
заменил на:
`this.dictionary = dictionary;`
