### ISSUE TITLE
элементы словаря не должны быть свойствами LevelParser

### ISSUE THREAD

**Issue by frontgirl** [BRust1981/NetologyDiplom#9]
https://github.com/BRust1981/NetologyDiplom/blob/43e1bbcb4b4355f6adc49ca7cd8cad04ec24b1cb/game.js#L314

Вытекает из предыдущего пункта, нужно делать поиск в this.dictionary[objSym]

**Comment by BRust1981** [comment]
Ок. Заменил на свойство-объект dictionary.
